blank_issues_enabled: false
contact_links:
    - name: ⚠️ Source issue
      url: https://github.com/KotatsuApp/kotatsu-parsers/issues/new
      about: If you have a problem with a specific **manga source** or want to propose a new one, please open an issue in the kotatsu-parsers repository instead
